### PR TITLE
Changed location of each remove button to the bottom of each column.

### PR DESCRIPTION
**Pull request by IStallcup**
Someone should take a look at this and make sure it looks good! Works for me though. Moving on to the move functionality.

### CODE REVIEW

**Comment by IStallcup** [comment]
Solves issue #2 I believe.

**Comment by athai** [comment]
Looks good! Although, weren't we going to rename 'remove' to 'discard', or was that just me?

**Comment by IStallcup** [comment]
Very true! Fixing it now.

**Comment by kannabanana** [comment]
Nice job guys..now just need it to look pretty and add the error stuff.

**Pull request closed without merging**
